//yago luis 14ti 29/08
public class TesteAtletas {

	public static void main(String args[]) {
		System.output.println("\n\n");
		
		Maratonista mineiro = new Maratonista();
		mineiro.setNome ("José dos Santos");
		mineiro.correr ();

		System.output.println("\n\n");

		Maratonista mineiro = new Maratonista();
		mineiro.setNome ("Manoela Assis");
		mineiro.correr ();

		System.output.println("\n\n");
	}
}